openapi: 3.0.0
info:
  title: Notification API
  version: 1.0.0
paths:
  /notifications:
    post:
      summary: Send a notification
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/NotificationRequest"
            example:
              type: "email"
              to: "user@example.com"
              subject: "Weekend Grocery Offers!"
              message: "Check out these amazing grocery deals this weekend!"
              cardTypes: ["Visa"]
              category: ["Supermarket", "Dining"]
              startDate: "2025-07-23"
              endDate: "2025-08-01"
      responses:
        '200':
          description: Notification sent successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: success

components:
  schemas:
    NotificationRequest:
      type: object
      required:
        - type
        - to
      properties:
        type:
          type: string
          description: Notification type (e.g., email, sms)
          example: email
        to:
          type: string
          description: Recipient email address
          example: user@example.com
        subject:
          type: string
          description: Subject line of the notification
          example: Weekend Grocery Offers!
        message:
          type: string
          description: Content of the message
          example: Check out these amazing grocery deals this weekend!
        cardTypes:
          type: array
          description: Filter by card types
          items:
            type: string
          example: ["Visa"]
        category:
          type: array
          description: One or more promotion categories
          items:
            type: string
            enum:
              - Supermarket
              - Dining
              - Travel
              - Electronics
              - Fashion
              - Health & Wellness
              - Entertainment
              - Education
              - Other
          example: ["Supermarket", "Dining"]
        startDate:
          type: string
          format: date
          description: Filter promotions starting from this date
          example: "2025-07-23"
        endDate:
          type: string
          format: date
          description: Filter promotions ending before or on this date
          example: "2025-08-01"
        promotions:
          type: array
          items:
            $ref: "#/components/schemas/Promotion"

    Promotion:
      type: object
      required:
        - company_name
        - card_type
        - category
        - description
        - validity
        - promotion_details
        - terms_and_conditions
        - promo_code
      properties:
        company_name:
          type: string
          example: FreshMart Supermarket
        card_type:
          type: string
          example: Visa
        category:
          type: string
          example: Supermarket
        description:
          type: string
          example: Get 15% cashback on grocery shopping every weekend.
        validity:
          type: object
          required:
            - start_date
            - end_date
          properties:
            start_date:
              type: string
              format: date
              example: "2025-07-23"
            end_date:
              type: string
              format: date
              example: "2025-08-11"
        promotion_details:
          type: string
          example: Get 15% cashback on grocery shopping every weekend. Valid at selected merchants only.
        terms_and_conditions:
          type: string
          example: Terms apply. Offer valid only during the mentioned period. Subject to change without notice.
        promo_code:
          type: string
          example: BOC-VISA-15GROC
